name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [ macos-latest ]

    steps:
    - name: Select latest Xcode
      run: "sudo xcode-select -s /Applications/Xcode_12.4.app"

    - name: Install make
      run: |
        brew install make
        echo "/usr/local/opt/make/libexec/gnubin" >> $GITHUB_PATH

    - uses: actions/checkout@v2

    - name: Archive
      run: |
        make release

    - name: Upload artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: App
        path: ./dist
