name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [ macos-latest ]

    steps:
    - name: Select latest Xcode
      run: "sudo xcode-select -s /Applications/Xcode_11.4.app"

    - uses: actions/checkout@v2

    - name: Archive
      run: |
        make release

    - name: Upload artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: App
        path: ./dist
